// AUTO-GENERATED BY tools/generate_types.py
// DO NOT EDIT MANUALLY

export interface PayeeLocationsResponse {
  data: {
    payee_locations: PayeeLocation[];
  };
}

export interface PayeeLocationResponse {
  data: {
    payee_location: PayeeLocation;
  };
}

export interface PayeeLocation {
  id: string;
  payee_id: string;
  latitude: string;
  longitude: string;
  deleted: boolean;
}
