// AUTO-GENERATED BY tools/generate_types.py
// DO NOT EDIT MANUALLY

export interface PayeesResponse {
  data: {
    payees: Payee[];
    server_knowledge: number;
  };
}

export interface PayeeResponse {
  data: {
    payee: Payee;
  };
}

export interface Payee {
  id: string;
  name: string;
  transfer_account_id?: string | null;
  deleted: boolean;
}
