// AUTO-GENERATED BY tools/generate_types.py
// DO NOT EDIT MANUALLY

export type ScheduledTransactionFrequency = ("never" | "daily" | "weekly" | "everyOtherWeek" | "twiceAMonth" | "every4Weeks" | "monthly" | "everyOtherMonth" | "every3Months" | "every4Months" | "twiceAYear" | "yearly" | "everyOtherYear");
