// AUTO-GENERATED BY tools/generate_types.py
// DO NOT EDIT MANUALLY

import type { ScheduledTransactionDetail } from "./ScheduledTransactionDetail.js";

export interface ScheduledTransactionsResponse {
  data: {
    scheduled_transactions: ScheduledTransactionDetail[];
    server_knowledge: number;
  };
}
