// AUTO-GENERATED BY tools/generate_types.py
// DO NOT EDIT MANUALLY

export interface ErrorResponse {
  error: ErrorDetail;
}

export interface ErrorDetail {
  id: string;
  name: string;
  detail: string;
}
