// AUTO-GENERATED BY tools/generate_types.py
// DO NOT EDIT MANUALLY

import type { Category } from "./Category.js";

export interface SaveCategoryResponse {
  data: {
    category: Category;
    server_knowledge: number;
  };
}

export interface PatchCategoryWrapper {
  category: SaveCategory;
}

export interface SaveCategory {
  name?: string | null;
  note?: string | null;
  category_group_id?: string;
  goal_target?: number | null;
}
