// AUTO-GENERATED BY tools/generate_types.py
// DO NOT EDIT MANUALLY

export interface PatchMonthCategoryWrapper {
  category: SaveMonthCategory;
}

export interface SaveMonthCategory {
  budgeted: number;
}
