// AUTO-GENERATED BY tools/generate_types.py
// DO NOT EDIT MANUALLY

import type { UserResponse } from '../user/User.js';
import type { ErrorResponse } from '../common/ErrorResponse.js';
import type { BudgetSummaryResponse } from '../budgets/BudgetSummary.js';
import type { BudgetDetailResponse } from '../budgets/BudgetDetail.js';
import type { BudgetSettingsResponse } from '../budgets/BudgetSettings.js';
import type { AccountsResponse, AccountResponse } from '../accounts/Account.js';
import type { PostAccountWrapper } from '../accounts/SaveAccount.js';
import type { CategoriesResponse } from '../categories/CategoryGroupWithCategories.js';
import type { CategoryResponse } from '../categories/Category.js';
import type { PatchCategoryWrapper, SaveCategoryResponse } from '../categories/SaveCategory.js';
import type { PatchMonthCategoryWrapper } from '../categories/SaveMonthCategory.js';
import type { PayeesResponse, PayeeResponse } from '../payees/Payee.js';
import type { SavePayeeResponse, PatchPayeeWrapper } from '../payees/SavePayee.js';
import type { PayeeLocationsResponse, PayeeLocationResponse } from '../payee-locations/PayeeLocation.js';
import type { MonthSummariesResponse } from '../months/MonthSummary.js';
import type { MonthDetailResponse } from '../months/MonthDetail.js';
import type { TransactionsResponse } from '../transactions/TransactionsResponse.js';
import type { PostTransactionsWrapper } from '../transactions/NewTransaction.js';
import type { PatchTransactionsWrapper } from '../transactions/PatchTransactions.js';
import type { SaveTransactionsResponse } from '../transactions/SaveTransactionsResponse.js';
import type { TransactionsImportResponse } from '../transactions/BulkTransactions.js';
import type { TransactionResponse } from '../transactions/TransactionDetail.js';
import type { PutTransactionWrapper } from '../transactions/SaveTransaction.js';
import type { HybridTransactionsResponse } from '../transactions/HybridTransaction.js';
import type { ScheduledTransactionsResponse } from '../scheduled-transactions/ScheduledTransactionsResponse.js';
import type { PostScheduledTransactionWrapper } from '../scheduled-transactions/SaveScheduledTransaction.js';
import type { ScheduledTransactionResponse } from '../scheduled-transactions/ScheduledTransactionDetail.js';
import type { PutScheduledTransactionWrapper } from '../scheduled-transactions/SaveScheduledTransaction.js';

export interface Paths {
  "/user": {
    get: {
      responses: {
        200: UserResponse;
        default: ErrorResponse;
      };
    };
  };
  "/budgets": {
    get: {
      parameters: {
        query: {
          include_accounts?: boolean;
        };
      };
      responses: {
        200: BudgetSummaryResponse;
        404: ErrorResponse;
        default: ErrorResponse;
      };
    };
  };
  "/budgets/{budget_id}": {
    get: {
      parameters: {
        path: {
          budget_id: string;
        };
        query: {
          last_knowledge_of_server?: number;
        };
      };
      responses: {
        200: BudgetDetailResponse;
        404: ErrorResponse;
        default: ErrorResponse;
      };
    };
  };
  "/budgets/{budget_id}/settings": {
    get: {
      parameters: {
        path: {
          budget_id: string;
        };
      };
      responses: {
        200: BudgetSettingsResponse;
        404: ErrorResponse;
        default: ErrorResponse;
      };
    };
  };
  "/budgets/{budget_id}/accounts": {
    get: {
      parameters: {
        path: {
          budget_id: string;
        };
        query: {
          last_knowledge_of_server?: number;
        };
      };
      responses: {
        200: AccountsResponse;
        404: ErrorResponse;
        default: ErrorResponse;
      };
    };
    post: {
      parameters: {
        path: {
          budget_id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": PostAccountWrapper;
        };
      };
      responses: {
        201: AccountResponse;
        400: ErrorResponse;
      };
    };
  };
  "/budgets/{budget_id}/accounts/{account_id}": {
    get: {
      parameters: {
        path: {
          budget_id: string;
          account_id: string;
        };
      };
      responses: {
        200: AccountResponse;
        404: ErrorResponse;
        default: ErrorResponse;
      };
    };
  };
  "/budgets/{budget_id}/categories": {
    get: {
      parameters: {
        path: {
          budget_id: string;
        };
        query: {
          last_knowledge_of_server?: number;
        };
      };
      responses: {
        200: CategoriesResponse;
        404: ErrorResponse;
        default: ErrorResponse;
      };
    };
  };
  "/budgets/{budget_id}/categories/{category_id}": {
    get: {
      parameters: {
        path: {
          budget_id: string;
          category_id: string;
        };
      };
      responses: {
        200: CategoryResponse;
        404: ErrorResponse;
        default: ErrorResponse;
      };
    };
    patch: {
      parameters: {
        path: {
          budget_id: string;
          category_id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": PatchCategoryWrapper;
        };
      };
      responses: {
        200: SaveCategoryResponse;
        400: ErrorResponse;
      };
    };
  };
  "/budgets/{budget_id}/months/{month}/categories/{category_id}": {
    get: {
      parameters: {
        path: {
          budget_id: string;
          month: string;
          category_id: string;
        };
      };
      responses: {
        200: CategoryResponse;
        404: ErrorResponse;
        default: ErrorResponse;
      };
    };
    patch: {
      parameters: {
        path: {
          budget_id: string;
          month: string;
          category_id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": PatchMonthCategoryWrapper;
        };
      };
      responses: {
        200: SaveCategoryResponse;
        400: ErrorResponse;
      };
    };
  };
  "/budgets/{budget_id}/payees": {
    get: {
      parameters: {
        path: {
          budget_id: string;
        };
        query: {
          last_knowledge_of_server?: number;
        };
      };
      responses: {
        200: PayeesResponse;
        404: ErrorResponse;
        default: ErrorResponse;
      };
    };
  };
  "/budgets/{budget_id}/payees/{payee_id}": {
    get: {
      parameters: {
        path: {
          budget_id: string;
          payee_id: string;
        };
      };
      responses: {
        200: PayeeResponse;
        404: ErrorResponse;
        default: ErrorResponse;
      };
    };
    patch: {
      parameters: {
        path: {
          budget_id: string;
          payee_id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": PatchPayeeWrapper;
        };
      };
      responses: {
        200: SavePayeeResponse;
        400: ErrorResponse;
      };
    };
  };
  "/budgets/{budget_id}/payee_locations": {
    get: {
      parameters: {
        path: {
          budget_id: string;
        };
      };
      responses: {
        200: PayeeLocationsResponse;
        404: ErrorResponse;
        default: ErrorResponse;
      };
    };
  };
  "/budgets/{budget_id}/payee_locations/{payee_location_id}": {
    get: {
      parameters: {
        path: {
          budget_id: string;
          payee_location_id: string;
        };
      };
      responses: {
        200: PayeeLocationResponse;
        404: ErrorResponse;
        default: ErrorResponse;
      };
    };
  };
  "/budgets/{budget_id}/payees/{payee_id}/payee_locations": {
    get: {
      parameters: {
        path: {
          budget_id: string;
          payee_id: string;
        };
      };
      responses: {
        200: PayeeLocationsResponse;
        404: ErrorResponse;
        default: ErrorResponse;
      };
    };
  };
  "/budgets/{budget_id}/months": {
    get: {
      parameters: {
        path: {
          budget_id: string;
        };
        query: {
          last_knowledge_of_server?: number;
        };
      };
      responses: {
        200: MonthSummariesResponse;
        404: ErrorResponse;
        default: ErrorResponse;
      };
    };
  };
  "/budgets/{budget_id}/months/{month}": {
    get: {
      parameters: {
        path: {
          budget_id: string;
          month: string;
        };
      };
      responses: {
        200: MonthDetailResponse;
        404: ErrorResponse;
        default: ErrorResponse;
      };
    };
  };
  "/budgets/{budget_id}/transactions": {
    get: {
      parameters: {
        path: {
          budget_id: string;
        };
        query: {
          since_date?: string;
          type?: ("uncategorized" | "unapproved");
          last_knowledge_of_server?: number;
        };
      };
      responses: {
        200: TransactionsResponse;
        400: ErrorResponse;
        404: ErrorResponse;
      };
    };
    post: {
      parameters: {
        path: {
          budget_id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": PostTransactionsWrapper;
        };
      };
      responses: {
        201: SaveTransactionsResponse;
        400: ErrorResponse;
        409: ErrorResponse;
      };
    };
    patch: {
      parameters: {
        path: {
          budget_id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": PatchTransactionsWrapper;
        };
      };
      responses: {
        209: SaveTransactionsResponse;
        400: ErrorResponse;
      };
    };
  };
  "/budgets/{budget_id}/transactions/import": {
    post: {
      parameters: {
        path: {
          budget_id: string;
        };
      };
      responses: {
        200: TransactionsImportResponse;
        201: TransactionsImportResponse;
        400: ErrorResponse;
      };
    };
  };
  "/budgets/{budget_id}/transactions/{transaction_id}": {
    get: {
      parameters: {
        path: {
          budget_id: string;
          transaction_id: string;
        };
      };
      responses: {
        200: TransactionResponse;
        404: ErrorResponse;
        default: ErrorResponse;
      };
    };
    put: {
      parameters: {
        path: {
          budget_id: string;
          transaction_id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": PutTransactionWrapper;
        };
      };
      responses: {
        200: TransactionResponse;
        400: ErrorResponse;
      };
    };
    delete: {
      parameters: {
        path: {
          budget_id: string;
          transaction_id: string;
        };
      };
      responses: {
        200: TransactionResponse;
        404: ErrorResponse;
      };
    };
  };
  "/budgets/{budget_id}/accounts/{account_id}/transactions": {
    get: {
      parameters: {
        path: {
          budget_id: string;
          account_id: string;
        };
        query: {
          since_date?: string;
          type?: ("uncategorized" | "unapproved");
          last_knowledge_of_server?: number;
        };
      };
      responses: {
        200: TransactionsResponse;
        404: ErrorResponse;
        default: ErrorResponse;
      };
    };
  };
  "/budgets/{budget_id}/categories/{category_id}/transactions": {
    get: {
      parameters: {
        path: {
          budget_id: string;
          category_id: string;
        };
        query: {
          since_date?: string;
          type?: ("uncategorized" | "unapproved");
          last_knowledge_of_server?: number;
        };
      };
      responses: {
        200: HybridTransactionsResponse;
        404: ErrorResponse;
        default: ErrorResponse;
      };
    };
  };
  "/budgets/{budget_id}/payees/{payee_id}/transactions": {
    get: {
      parameters: {
        path: {
          budget_id: string;
          payee_id: string;
        };
        query: {
          since_date?: string;
          type?: ("uncategorized" | "unapproved");
          last_knowledge_of_server?: number;
        };
      };
      responses: {
        200: HybridTransactionsResponse;
        404: ErrorResponse;
        default: ErrorResponse;
      };
    };
  };
  "/budgets/{budget_id}/months/{month}/transactions": {
    get: {
      parameters: {
        path: {
          budget_id: string;
          month: string;
        };
        query: {
          since_date?: string;
          type?: ("uncategorized" | "unapproved");
          last_knowledge_of_server?: number;
        };
      };
      responses: {
        200: TransactionsResponse;
        404: ErrorResponse;
        default: ErrorResponse;
      };
    };
  };
  "/budgets/{budget_id}/scheduled_transactions": {
    get: {
      parameters: {
        path: {
          budget_id: string;
        };
        query: {
          last_knowledge_of_server?: number;
        };
      };
      responses: {
        200: ScheduledTransactionsResponse;
        404: ErrorResponse;
        default: ErrorResponse;
      };
    };
    post: {
      parameters: {
        path: {
          budget_id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": PostScheduledTransactionWrapper;
        };
      };
      responses: {
        201: ScheduledTransactionResponse;
        400: ErrorResponse;
      };
    };
  };
  "/budgets/{budget_id}/scheduled_transactions/{scheduled_transaction_id}": {
    get: {
      parameters: {
        path: {
          budget_id: string;
          scheduled_transaction_id: string;
        };
      };
      responses: {
        200: ScheduledTransactionResponse;
        404: ErrorResponse;
        default: ErrorResponse;
      };
    };
    put: {
      parameters: {
        path: {
          budget_id: string;
          scheduled_transaction_id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": PutScheduledTransactionWrapper;
        };
      };
      responses: {
        200: ScheduledTransactionResponse;
        400: ErrorResponse;
      };
    };
    delete: {
      parameters: {
        path: {
          budget_id: string;
          scheduled_transaction_id: string;
        };
      };
      responses: {
        200: ScheduledTransactionResponse;
        404: ErrorResponse;
      };
    };
  };
}

export const EndpointMetadata = {
  "/user": ["get"],
  "/budgets": ["get"],
  "/budgets/{budget_id}": ["get"],
  "/budgets/{budget_id}/settings": ["get"],
  "/budgets/{budget_id}/accounts": ["get", "post"],
  "/budgets/{budget_id}/accounts/{account_id}": ["get"],
  "/budgets/{budget_id}/categories": ["get"],
  "/budgets/{budget_id}/categories/{category_id}": ["get", "patch"],
  "/budgets/{budget_id}/months/{month}/categories/{category_id}": ["get", "patch"],
  "/budgets/{budget_id}/payees": ["get"],
  "/budgets/{budget_id}/payees/{payee_id}": ["get", "patch"],
  "/budgets/{budget_id}/payee_locations": ["get"],
  "/budgets/{budget_id}/payee_locations/{payee_location_id}": ["get"],
  "/budgets/{budget_id}/payees/{payee_id}/payee_locations": ["get"],
  "/budgets/{budget_id}/months": ["get"],
  "/budgets/{budget_id}/months/{month}": ["get"],
  "/budgets/{budget_id}/transactions": ["get", "post", "patch"],
  "/budgets/{budget_id}/transactions/import": ["post"],
  "/budgets/{budget_id}/transactions/{transaction_id}": ["get", "put", "delete"],
  "/budgets/{budget_id}/accounts/{account_id}/transactions": ["get"],
  "/budgets/{budget_id}/categories/{category_id}/transactions": ["get"],
  "/budgets/{budget_id}/payees/{payee_id}/transactions": ["get"],
  "/budgets/{budget_id}/months/{month}/transactions": ["get"],
  "/budgets/{budget_id}/scheduled_transactions": ["get", "post"],
  "/budgets/{budget_id}/scheduled_transactions/{scheduled_transaction_id}": ["get", "put", "delete"],
} as const;
