// AUTO-GENERATED BY tools/generate_types.py
// DO NOT EDIT MANUALLY

export type AccountType = ("checking" | "savings" | "cash" | "creditCard" | "lineOfCredit" | "otherAsset" | "otherLiability" | "mortgage" | "autoLoan" | "studentLoan" | "personalLoan" | "medicalDebt" | "otherDebt");
