// AUTO-GENERATED BY tools/generate_types.py
// DO NOT EDIT MANUALLY

import type { DateFormat } from '../common/DateFormat.js';
import type { CurrencyFormat } from '../common/CurrencyFormat.js';

export interface BudgetSettingsResponse {
  data: {
    settings: BudgetSettings;
  };
}

export interface BudgetSettings {
  date_format: DateFormat;
  currency_format: CurrencyFormat;
}
