// AUTO-GENERATED BY tools/generate_types.py
// DO NOT EDIT MANUALLY

import type { BudgetSummary } from './BudgetSummary.js';
import type { Account } from '../accounts/Account.js';
import type { Payee } from '../payees/Payee.js';
import type { PayeeLocation } from '../payee-locations/PayeeLocation.js';
import type { CategoryGroup } from '../categories/CategoryGroup.js';
import type { Category } from '../categories/Category.js';
import type { MonthDetail } from '../months/MonthDetail.js';
import type { TransactionSummary } from '../transactions/TransactionSummary.js';
import type { SubTransaction } from '../transactions/SubTransaction.js';
import type { ScheduledTransactionSummary } from '../scheduled-transactions/ScheduledTransactionSummary.js';
import type { ScheduledSubTransaction } from '../scheduled-transactions/ScheduledSubTransaction.js';

export interface BudgetDetailResponse {
  data: {
    budget: BudgetDetail;
    server_knowledge: number;
  };
}

export type BudgetDetail = (BudgetSummary & {
  accounts?: Account[];
  payees?: Payee[];
  payee_locations?: PayeeLocation[];
  category_groups?: CategoryGroup[];
  categories?: Category[];
  months?: MonthDetail[];
  transactions?: TransactionSummary[];
  subtransactions?: SubTransaction[];
  scheduled_transactions?: ScheduledTransactionSummary[];
  scheduled_subtransactions?: ScheduledSubTransaction[];
});
