// AUTO-GENERATED BY tools/generate_types.py
// DO NOT EDIT MANUALLY

import type { DateFormat } from '../common/DateFormat.js';
import type { CurrencyFormat } from '../common/CurrencyFormat.js';
import type { Account } from '../accounts/Account.js';

export interface BudgetSummaryResponse {
  data: {
    budgets: BudgetSummary[];
    default_budget?: BudgetSummary;
  };
}

export interface BudgetSummary {
  id: string;
  name: string;
  last_modified_on?: string;
  first_month?: string;
  last_month?: string;
  date_format?: DateFormat;
  currency_format?: CurrencyFormat;
  accounts?: Account[];
}
