// AUTO-GENERATED BY tools/generate_types.py
// DO NOT EDIT MANUALLY

import type { SaveTransactionWithOptionalFields } from "./SaveTransactionWithOptionalFields.js";

export interface PostTransactionsWrapper {
  transaction?: NewTransaction;
  transactions?: NewTransaction[];
}

export type NewTransaction = SaveTransactionWithOptionalFields & {
  import_id?: string | null;
};
