// AUTO-GENERATED BY tools/generate_types.py
// DO NOT EDIT MANUALLY

import type { SaveTransactionWithOptionalFields } from './SaveTransactionWithOptionalFields.js';

export interface PatchTransactionsWrapper {
  transactions: SaveTransactionWithIdOrImportId[];
}

export type SaveTransactionWithIdOrImportId = ({
  id?: string | null;
  import_id?: string | null;
} & SaveTransactionWithOptionalFields);
