// AUTO-GENERATED BY tools/generate_types.py
// DO NOT EDIT MANUALLY

import type { SaveTransactionWithOptionalFields } from './SaveTransactionWithOptionalFields.js';

export interface PutTransactionWrapper {
  transaction: ExistingTransaction;
}

export type ExistingTransaction = ({
} & SaveTransactionWithOptionalFields);
