// AUTO-GENERATED BY tools/generate_types.py
// DO NOT EDIT MANUALLY

import type {
  TransactionClearedStatus,
  TransactionFlagColor,
} from "./TransactionEnums.js";
import type { SaveSubTransaction } from "./SaveSubTransaction.js";

export interface SaveTransactionWithOptionalFields {
  account_id?: string;
  date?: string;
  amount?: number;
  payee_id?: string | null;
  payee_name?: string | null;
  category_id?: string | null;
  memo?: string | null;
  cleared?: TransactionClearedStatus;
  approved?: boolean;
  flag_color?: TransactionFlagColor;
  subtransactions?: SaveSubTransaction[];
}
