// AUTO-GENERATED BY tools/generate_types.py
// DO NOT EDIT MANUALLY

export interface SaveSubTransaction {
  amount: number;
  payee_id?: string | null;
  payee_name?: string | null;
  category_id?: string | null;
  memo?: string | null;
}
