// AUTO-GENERATED BY tools/generate_types.py
// DO NOT EDIT MANUALLY

export type TransactionFlagColor = ("red" | "orange" | "yellow" | "green" | "blue" | "purple" | "" | null);

export type TransactionFlagName = string | null;

export type TransactionClearedStatus = ("cleared" | "uncleared" | "reconciled");
