// AUTO-GENERATED BY tools/generate_types.py
// DO NOT EDIT MANUALLY

import type { TransactionDetail } from './TransactionDetail.js';

export interface TransactionsResponse {
  data: {
    transactions: TransactionDetail[];
    server_knowledge: number;
  };
}
