// AUTO-GENERATED BY tools/generate_types.py
// DO NOT EDIT MANUALLY

import type {
  TransactionClearedStatus,
  TransactionFlagColor,
  TransactionFlagName,
} from "./TransactionEnums.js";

export interface TransactionSummary {
  id: string;
  date: string;
  amount: number;
  memo?: string | null;
  cleared: TransactionClearedStatus;
  approved: boolean;
  flag_color?: TransactionFlagColor;
  flag_name?: TransactionFlagName;
  account_id: string;
  payee_id?: string | null;
  category_id?: string | null;
  transfer_account_id?: string | null;
  transfer_transaction_id?: string | null;
  matched_transaction_id?: string | null;
  import_id?: string | null;
  import_payee_name?: string | null;
  import_payee_name_original?: string | null;
  debt_transaction_type?:
    | "payment"
    | "refund"
    | "fee"
    | "interest"
    | "escrow"
    | "balanceAdjustment"
    | "credit"
    | "charge"
    | null;
  deleted: boolean;
}
