// AUTO-GENERATED BY tools/generate_types.py
// DO NOT EDIT MANUALLY

import type { MonthSummary } from './MonthSummary.js';
import type { Category } from '../categories/Category.js';

export interface MonthDetailResponse {
  data: {
    month: MonthDetail;
  };
}

export type MonthDetail = (MonthSummary & {
  categories: Category[];
});
