// AUTO-GENERATED BY tools/generate_types.py
// DO NOT EDIT MANUALLY

export interface MonthSummariesResponse {
  data: {
    months: MonthSummary[];
    server_knowledge: number;
  };
}

export interface MonthSummary {
  month: string;
  note?: string | null;
  income: number;
  budgeted: number;
  activity: number;
  to_be_budgeted: number;
  age_of_money?: number | null;
  deleted: boolean;
}
